# Docker Compose for Qwen 2.5 using Ollama (Recommended - Simplest)
version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: qwen-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # Optional: Web UI for Ollama
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: qwen-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - webui_data:/app/backend/data
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
  webui_data:
